src/com/xmut/estore/domain/ShoppingCart.java
package com.xmut.estore.domain;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import com.xmut.estore.domain.Computer;
import com.xmut.estore.domain.ShoppingCartItem;

public class ShoppingCart {
	
	private Map<Integer, ShoppingCartItem> computers = new HashMap<>();
	
	/**
	 * 修改指定购物项的数量
	 */
	public void updateItemQuantity(Integer id, int quantity){
		ShoppingCartItem sci =computers.get(id);
		if(sci != null){
			sci.setQuantity(quantity);
		}
	}
	
	/**
	 * 移除指定的购物项
	 * @param id
	 */
	public void removeItem(Integer id){
		computers.remove(id);
	}
	
	/**
	 * 清空购物车
	 */
	public void clear(){
		computers.clear();
	}
	
	/**
	 * 返回购物车是否为空
	 * @return
	 */
	public boolean isEmpty(){
		return computers.isEmpty();
	}
	
	/**
	 * 获取购物车中所有的商品的总的钱数
	 * @return
	 */
	public float getTotalMoney(){
		float total = 0;
		
		for(ShoppingCartItem sci: getItems()){
			total += sci.getItemMoney();
		}
		
		return total;
	}
	
	/**
	 * 获取购物车中的所有的 ShoppingCartItem 组成的集合
	 * @return
	 */
	public Collection<ShoppingCartItem> getItems(){
		return computers.values();
	}
	
	/**
	 * 返回购物车中商品的总数量
	 * @return
	 */
	public int getComputerNumber(){
		int total = 0;
		
		for(ShoppingCartItem sci: computers.values()){
			total += sci.getQuantity();
		}
		
		return total;
	}
	
	public Map<Integer, ShoppingCartItem> getComputers() {
		return computers;
	}
	
	/**
	 * 检验购物车中是否有 id 指定的商品		
	 * @param id
	 * @return
	 */
	public boolean hasComputer(Integer id){
		return computers.containsKey(id);
	}		
			
	/**
	 * 向购物车中添加一件商品		
	 * @param computer
	 */
	public void addComputer(Computer computer){
		//1. 检查购物车中有没有该商品, 若有, 则使其数量 +1, 若没有, 
		//新创建其对应的 ShoppingCartItem, 并把其加入到 computers 中
		ShoppingCartItem sci = computers.get(computer.getId());
		
		if(sci == null){
			sci = new ShoppingCartItem(computer);
			computers.put(computer.getId(), sci);
		}else{
			sci.increment();
		}
	}
}

WebContent/commons/footer.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<hr>
		<footer class="footer">
	      <div class="container">
	      <div id="back-to-top" href="#">
	              	<span class="glyphicon glyphicon-triangle-top"></span>&nbsp;回到顶部
	       </div>
	        <p class="text-muted">&copy; 2018 EStore Company, Inc. 
		        
          	</p>
	       
	      </div>
	      
    	</footer>

WebContent/commons/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<nav class="navbar navbar-default navbar-static-top">
	      <div class="container">
		        <div class="navbar-header">
		          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button>
		          <a class="navbar-brand" href="computerServlet?method=getComputers"><span class="glyphicon glyphicon-blackboard"></span> EStore百脑汇</a>
		        </div>
		        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
		          <ul class="nav navbar-nav">
		            <li class="active"><a href="computerServlet?method=getComputers">首页</a></li>
		            <li><a href="#about">关于</a></li>
		            <li><a href="#contact">联系我们</a></li>
		          </ul>
		          <ul class="nav navbar-nav navbar-right">
      				<li role="presentation" ><a href="computerServlet?method=forwardPage&page=cart&pageNo=${computerpage.pageNo }"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;购物车&nbsp;<span class="badge">${sessionScope.ShoppingCart.computerNumber }</span></a></li>
        		
	       	 		<li class="dropdown">
		          		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;admin<span class="caret"></span></a>
		          		<ul class="dropdown-menu">
				            <li><a href="#">我的账号</a></li>
				            <li><a href="#">我的订单</a></li>
				            <li><a href="#">账号余额</a></li>
				            <li role="separator" class="divider"></li>
				            <li><a href="#">退出</a></li>
		          		</ul>
	        		</li>
      			  </ul>
		        </div><!--/.nav-collapse -->
	      </div>
    	</nav>

WebContent/commons/queryCondition.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<script type="text/javascript">
	
	$(function(){
		$("a").each(function(){
			this.onclick = function(){
				var serializeVal = $(":hidden").serialize();
				var href = this.href + "&" + serializeVal;
				window.location.href = href;			
				return false;
			};
		});
	});	
	
</script>

<input type="hidden" name="minPrice" value="${param.minPrice }"/>
<input type="hidden" name="maxPrice" value="${param.maxPrice }"/>
	